name: my first workflow

on: push

jobs:
  first_job: 
    runs-on: ubuntu-latest
    steps: 
    - name: checkout repo
      uses: actions/checkout@v4
      
    - name: Welcome! Message 
      run:  echo "This is My First Github Actions Job"

    - name: Read Files
      run: ls -lart

    - name: 
      run: cat READ.md
