name: my first workflow

on: push

jobs:
  first_job: 
    runs-on: ubuntu-latest
    steps: 
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Welcome & Read Message 
      run: |
       echo "This is My First Github Actions Job"
       ls -lart
       cat README.md

    - name: Generate ASCII Artwork
      run: cowsay -f crow "Run for cover, I am a CROW...kakaka" >> crow.txt


