name: Generate ASCII Artwork

on: 
    push

jobs: 
    ascii_job: 
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: install cowsay program
              run: sudo apt-get install cowsay -y

            - name: execute cowsay CMD
              run: cowsay -f crow "Run for cover, I am a CROW...kakaka" >> crow.txt

            - name: test file exists
              run: grep -i "crow" crow.txt

            - name: read file
              run: cat crow.txt

            - name: checkout repo files
              run: ls -lart