name: Workflow Filters & Activities

on: 
    workflow_dispatch: 
    # schedule:
    #     - cron: "*/59 * * * *"
    push: 
        # branches-ignore: 
        #     - feature/*      # feature/add-music, feature/updateImages
        #     - test/**        # test/ui/index, test/checkout/payment/
        branches: 
            - main
            - '!features/*'  # ignoring pushing to any branch name starting with feature using !
    pull_request: 
        types: 
            - opened
            - closed
        paths-ignore:        # workflow will only run when a pull request that includes a change on any files other than README.md
            - README.md
        branches:            # configures your workflow to only run on pull requests that targets specific branches
            - main

jobs: 
    hello: 
        runs-on: ubuntu-latest
        steps:
            - run: echo this workflow/job/step is executed for the event type - ${{ github.event_name }}